services:
  # === WEB SERVICE (API PRINCIPAL) ===
  - type: web
    name: reservas-umg-api
    env: node
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVarGroups:
      - reservas-umg-env  # Grupo compartido de variables

  # === WORKER: GENERADOR DE PDF ===
  - type: worker
    name: reservas-umg-pdf-worker
    env: node
    buildCommand: "npm install"
    startCommand: "node workers/pdfWorker.js"
    envVarGroups:
      - reservas-umg-env

  # === WORKER: ENVÍO DE CORREOS ===
  - type: worker
    name: reservas-umg-email-worker
    env: node
    buildCommand: "npm install"
    startCommand: "node workers/emailWorker.js"
    envVarGroups:
      - reservas-umg-env