services:
  # === WEB SERVICE (API) ===
  - type: web
    name: reservas-umg-api
    env: node
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVars:
      - fromGroup: reservas-umg-env

  # === WORKER: GENERADOR DE PDF ===
  - type: worker
    name: reservas-umg-pdf-worker
    env: node
    buildCommand: "npm install"
    startCommand: "node workers/pdfWorker.js"
    envVars:
      - fromGroup: reservas-umg-env

  # === WORKER: ENVÍO DE EMAILS ===
  - type: worker
    name: reservas-umg-email-worker
    env: node
    buildCommand: "npm install"
    startCommand: "node workers/emailWorker.js"
    envVars:
      - fromGroup: reservas-umg-env
